version: '3.8'

include:
  - proxy.yaml

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.python
    image: web:local
    container_name: web-app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=web
      - MYSQL_PASSWORD=web-secret
      - MYSQL_DATABASE=example
    networks:
      backend:
        ipv4_address: 172.20.0.5

  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root-secret
      - MYSQL_DATABASE=example
      - MYSQL_USER=web
      - MYSQL_PASSWORD=web-secret
    env_file:
      - .env
    networks:
      backend:
        ipv4_address: 172.20.0.10
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot-secret"]
      timeout: 20s
      retries: 10
volumes:
  db_data:
